services:
  consumer:
    image: sarath254/consumer:latest
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_USERNAME=WFDAKMLCZKNMEBJE
      - KAFKA_SASL_PASSWORD=k3Za/moI21uOwRip2O1yk1UBThlQelOP8dMzycgj03nM3PqatTrR3vKGUmcx2JzO
      - KAFKA_GROUP_ID=group11
      - KAFKA_AUTO_OFFSET_RESET=earliest
    command: ["python", "consumer.py"]
